app: # 应用基本配置
  env: "local" # 环境名称
  port: 8888 # 服务监听端口号
  app_name: "package-gin-framework" # 应用名称
  app_url: "http://localhost" # 应用域名
log: # 日志
  level: "info" # 日志等级
  root_dir: "./storage/logs" # 日志根目录
  filename: "app.log" # 日志文件名
  format: "" # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件的最大大小(MB)
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩
